name: Connect to perchnet private infrastructure
on:
    workflow_call:
        inputs:
            load_op:
                required: false
                type: boolean
                default: true
            tailscale_tags:
                required: false
                type: string
                default: "tag:github_runner"

jobs:
  connect:
    name: "connect"
    runs-on: ubuntu-latest
    steps:
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v2

      - name: Load secrets
        id: load-secrets
        uses: 1password/load-secrets-action@v3
        with:
          export-env: false # Export loaded secrets as environment variables
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          TF_ENCRYPT_PASSPHRASE: "op://perchnet/tf_encrypt_passphrase/password"
          TF_API_TOKEN: "op://perchnet/terraform-token-github-actions/credential"
          TS_OAUTH_CLIENT_ID: "op://perchnet/tailscale-oauth-github-runner/username"
          TS_OAUTH_CLIENT_SECRET: "op://perchnet/tailscale-oauth-github-runner/credential"
          TF_VAR_onepassword_sdk_token: "op://perchnet/1p-terraform/credential"
          #SSH_PRIVATE_KEY: "op://perchnet/proxmox-ssh/private key?ssh-format=openssh"

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ steps.load-secrets.outputs.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ steps.load-secrets.outputs.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:github-runner
          use-cache: "true"
          #args: '--accept-routes'
    
      - run: tailscale ping pve1.shark-perch.ts.net